(() => {
  const OG = window.OG;

  const LABELS = [
    'ai overview',
    'ai overviews',
    'ai-powered overview',
    'ai powered overview',
    'generated by ai',
    'ai responses may include mistakes',
    'search labs',
    'ai mode',
  ];

  const SACRED = new Set([
    'rcnt', 'center_col', 'search', 'rso', 'main', 'cnt', 'appbar', 'topstuff',
    'taw', 'bres', 'botstuff', 'extrares', 'foot', 'gsr', 'rhs', 'tvcap',
  ]);

  function isSacred(node) {
    return node === document.body || node === document.documentElement || SACRED.has(node.id);
  }

  function tooImportantToHide(node) {
    if (node.matches('html,body,form,header,nav')) return true;
    if (node.querySelector('input[name="q"],textarea[name="q"],form[role="search"],#searchform,#rso,#center_col,#rcnt')) return true;
    return node.querySelectorAll('h3').length > 1;
  }

  const normalize = (s) => s.replace(/\s+/g, ' ').trim().toLowerCase();

  function resultBlock(node) {
    let cur = node;
    for (let steps = 0; cur.parentElement && steps < 12; steps++) {
      const parent = cur.parentElement;
      if (isSacred(parent)) return isSacred(cur) ? null : cur;
      cur = parent;
    }
    return null;
  }

  function looksLikeAiLabel(text) {
    const t = normalize(text);
    if (!t || t.length > 80) return false;
    return LABELS.some((l) => t === l || t.startsWith(l));
  }

  function hide(node, why) {
    if (isSacred(node) || tooImportantToHide(node)) return false;
    if (node.getAttribute('data-og-hidden') === 'ai') return false;
    node.setAttribute('data-og-hidden', 'ai');
    OG.log('hid AI surface —', why, node);
    return true;
  }

  OG.purgeAI = function () {
    if (!OG.settings.hideAI) return;
    let hidden = 0;

    const candidates = OG.qsa(
      '#rcnt h1, #rcnt h2, #rcnt [role="heading"], #rcnt [aria-label], #rcnt span, #rcnt div[jsname] > span'
    );
    for (const node of candidates) {
      const label = node.getAttribute('aria-label') ?? '';
      const text = node.children.length === 0 ? node.textContent : '';
      if (!looksLikeAiLabel(label) && !looksLikeAiLabel(text)) continue;
      const block = resultBlock(node);
      if (block && hide(block, 'label: ' + normalize(label || text))) hidden++;
    }

    for (const link of OG.qsa('a[href*="/search"], a[href*="udm="]')) {
      const href = link.getAttribute('href');
      const label = normalize(link.textContent) || normalize(link.getAttribute('aria-label') ?? '');
      if (!href.includes('udm=50') && label !== 'ai mode' && label !== 'ai') continue;
      let item = link;
      for (let i = 0; i < 3; i++) {
        const parent = item.parentElement;
        if (!parent || isSacred(parent) || tooImportantToHide(parent)) break;
        if (parent.querySelectorAll('a').length > 1) break;
        if (normalize(parent.textContent).length > 40) break;
        item = parent;
      }
      if (isSacred(item) || tooImportantToHide(item)) continue;
      item.setAttribute('data-og-hidden', 'ai');
      hidden++;
    }

    for (const btn of OG.qsa('#searchform [role="button"], form[role="search"] [role="button"], .RNNXgb [role="button"]')) {
      const label = normalize(btn.getAttribute('aria-label') ?? '');
      if (!label.includes('ai mode') && !label.includes('ask ai') && !label.includes('gemini')) continue;
      if (tooImportantToHide(btn)) continue;
      btn.setAttribute('data-og-hidden', 'ai');
      hidden++;
    }

    if (hidden) OG.log('purge pass hid', hidden, 'node(s)');
  };
})();
